* configure.in, configure, debugger/mcs51/configure.in,   debugger/mcs51/configure, sim/ucsim/configure.in,   sim/ucsim/configure, sim/ucsim/aclocal.m4, src/SDCCutil.c:   preparations for *BSD and Solaris ports
git-svn-id: https://sdcc.svn.sourceforge.net/svnroot/sdcc/trunk/sdcc@5738 4a8a32a2-be11-0410-ad9d-d568d2c75423

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3809,9 +3809,14 @@ done
 # Macro definitions
 # ===========================================================================
 
-# adl_DD_COPT macro checks if the compiler specified as the 1st parameter
-# supports option specified as the 2nd parameter
-# For example: DD_CPORT(CXX, fPIC)
+# Check whether the compiler for the current language is SunPRO.
+
+
+
+# bor_IS_VALID_OPTION macro checks if the current compiler, selected by
+# AC_LANG, supports option specified as the 1st parameter. The test fails if
+# the compiler returns an error or in case something is writeen to stderr.
+# For example: bor_VALID_OPT(fPIC)
 
 
 
@@ -3879,76 +3884,139 @@ done
 
 # Checking characteristics of compilers and other programs
 # ===========================================================================
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether preprocessor accepts -MM or -M" >&5
+if test "$ac_cv_c_compiler_gnu" = "yes"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether preprocessor accepts -MM or -M" >&5
 $as_echo_n "checking whether preprocessor accepts -MM or -M... " >&6; }
 if test "${sdcc_cv_MM+set}" = set; then :
   $as_echo_n "(cached) " >&6
 else
   echo "#include <stdio.h>" >_test_.c
-echo "" >>_test_.c
-$CPP -v -MM _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  sdcc_cv_MM="-MM"
-else
-  sdcc_cv_MM="-M"
-fi
-rm -f _test_.*
+  echo "" >>_test_.c
+  $CPP -v -MM _test_.c 1>&5 2>&5
+  if test "$?" = "0"; then
+    sdcc_cv_MM="-MM"
+  else
+    sdcc_cv_MM="-M"
+  fi
+  rm -f _test_.*
 fi
 { $as_echo "$as_me:${as_lineno-$LINENO}: result: $sdcc_cv_MM" >&5
 $as_echo "$sdcc_cv_MM" >&6; }
-M_OR_MM=$sdcc_cv_MM
+  M_OR_MM=$sdcc_cv_MM
 
-
-# This is the first time when CFLAGS are set/modified!!
-
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether $CC accepts -ggdb" >&5
-$as_echo_n "checking whether $CC accepts -ggdb... " >&6; }
-if test "${sdcc_cv_CCggdb+set}" = set; then :
+  # This is the first time when CFLAGS are set/modified!!
+  ac_test_CFLAGS=${CFLAGS+set}
+bor_save_CFLAGS=$CFLAGS
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether $C accepts -ggdb" >&5
+$as_echo_n "checking whether $C accepts -ggdb... " >&6; }
+if test "${bor_cv_c_ggdb+set}" = set; then :
   $as_echo_n "(cached) " >&6
 else
-  cat >_test_.c <<EOF
-#include <stdio.h>
-void main(void) {}
-EOF
-$CC -v -ggdb -c _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  sdcc_cv_CCggdb="yes"
+  bor_save_c_werror_flag=$ac_c_werror_flag
+   ac_c_werror_flag=yes
+
+   CFLAGS="-ggdb"
+   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  bor_cv_c_ggdb=yes
 else
-  sdcc_cv_CCggdb="no"
+  bor_cv_c_ggdb=no
 fi
-rm -f _test_.* a.out
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+   ac_c_werror_flag=$bor_save_c_werror_flag
 fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $sdcc_cv_CCggdb" >&5
-$as_echo "$sdcc_cv_CCggdb" >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $bor_cv_c_ggdb" >&5
+$as_echo "$bor_cv_c_ggdb" >&6; }
+   CFLAGS=$bor_save_CFLAGS
 
-if test "$sdcc_cv_CCggdb" = "yes"; then
-  CFLAGS="-ggdb ${CFLAGS}"
-fi
+  if test "$bor_cv_c_ggdb" = "yes"; then
+    CFLAGS="-ggdb ${CFLAGS}"
+  fi
 
-
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether $CC accepts -pipe" >&5
-$as_echo_n "checking whether $CC accepts -pipe... " >&6; }
-if test "${sdcc_cv_CCpipe+set}" = set; then :
+  ac_test_CFLAGS=${CFLAGS+set}
+bor_save_CFLAGS=$CFLAGS
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether $C accepts -pipe" >&5
+$as_echo_n "checking whether $C accepts -pipe... " >&6; }
+if test "${bor_cv_c_pipe+set}" = set; then :
   $as_echo_n "(cached) " >&6
 else
-  cat >_test_.c <<EOF
-#include <stdio.h>
-void main(void) {}
-EOF
-$CC -v -pipe -c _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  sdcc_cv_CCpipe="yes"
-else
-  sdcc_cv_CCpipe="no"
-fi
-rm -f _test_.* a.out
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $sdcc_cv_CCpipe" >&5
-$as_echo "$sdcc_cv_CCpipe" >&6; }
+  bor_save_c_werror_flag=$ac_c_werror_flag
+   ac_c_werror_flag=yes
 
-if test "$sdcc_cv_CCpipe" = "yes"; then
-  CFLAGS="-pipe $CFLAGS"
+   CFLAGS="-pipe"
+   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  bor_cv_c_pipe=yes
+else
+  bor_cv_c_pipe=no
 fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+   ac_c_werror_flag=$bor_save_c_werror_flag
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $bor_cv_c_pipe" >&5
+$as_echo "$bor_cv_c_pipe" >&6; }
+   CFLAGS=$bor_save_CFLAGS
+
+  if test "$bor_cv_c_pipe" = "yes"; then
+    CFLAGS="-pipe $CFLAGS"
+  fi
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether we are using the SunPRO C compiler" >&5
+$as_echo_n "checking whether we are using the SunPRO C compiler... " >&6; }
+if test "${bor_cv_c_compiler_sunpro+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+#if !defined __SUNPRO_C && !defined __SUNPRO_CC
+       choke me
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  bor_compiler_sunpro=yes
+else
+  bor_compiler_sunpro=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+bor_cv_c_compiler_sunpro=$bor_compiler_sunpro
+
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $bor_cv_c_compiler_sunpro" >&5
+$as_echo "$bor_cv_c_compiler_sunpro" >&6; }
+  if test "$bor_cv_c_compiler_sunpro" = "yes"; then
+    M_OR_MM="-xM1"
+  fi
+fi
+
+
 
 
 # Checks for typedefs, structures, and compiler characteristics.
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -86,23 +86,38 @@ AC_CHECK_FUNCS(vsnprintf snprintf vsprintf mkstemp)
 # Macro definitions
 # ===========================================================================
 
-# adl_DD_COPT macro checks if the compiler specified as the 1st parameter
-# supports option specified as the 2nd parameter
-# For example: DD_CPORT(CXX, fPIC)
+# Check whether the compiler for the current language is SunPRO.
 
-AC_DEFUN([adl_DD_COPT], [
-AC_CACHE_CHECK(whether $$1 accepts -$2,sdcc_cv_$1$2,
-cat >_test_.c <<EOF
-#include <stdio.h>
-void main(void) {}
-EOF
-$$1 -v -$2 -c _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  sdcc_cv_$1$2="yes"
-else
-  sdcc_cv_$1$2="no"
-fi
-rm -f _test_.* a.out)
+AC_DEFUN(bor_IS_SUNPRO,
+[AC_CACHE_CHECK([whether we are using the SunPRO _AC_LANG compiler],
+  [bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro],
+  [_AC_COMPILE_IFELSE([AC_LANG_PROGRAM([], [[#if !defined __SUNPRO_C && !defined __SUNPRO_CC
+       choke me
+#endif
+]])],
+    [bor_compiler_sunpro=yes],
+    [bor_compiler_sunpro=no])
+bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro=$bor_compiler_sunpro
+])])
+
+# bor_IS_VALID_OPTION macro checks if the current compiler, selected by 
+# AC_LANG, supports option specified as the 1st parameter. The test fails if
+# the compiler returns an error or in case something is writeen to stderr.
+# For example: bor_VALID_OPT(fPIC)
+
+AC_DEFUN(bor_IS_VALID_OPTION,
+[ac_test_[]_AC_LANG_PREFIX[]FLAGS=${[]_AC_LANG_PREFIX[]FLAGS+set}
+bor_save_[]_AC_LANG_PREFIX[]FLAGS=$[]_AC_LANG_PREFIX[]FLAGS
+AC_CACHE_CHECK(whether $_AC_LANG_PREFIX accepts -$1, bor_cv_[]_AC_LANG_ABBREV[]_$1,
+  [bor_save_[]_AC_LANG_ABBREV[]_werror_flag=$ac_[]_AC_LANG_ABBREV[]_werror_flag
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=yes
+   
+   []_AC_LANG_PREFIX[]FLAGS="-$1"
+   AC_COMPILE_IFELSE([AC_LANG_PROGRAM()],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=yes],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=no])
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=$bor_save_[]_AC_LANG_ABBREV[]_werror_flag])
+   []_AC_LANG_PREFIX[]FLAGS=$bor_save_[]_AC_LANG_PREFIX[]FLAGS
 ])
 
 # This macro expands DIR and assigns it to RET.
@@ -316,29 +331,37 @@ $2=`echo "[$]$2" | sed 's,\\\\\\\\,\\\\,g'`
 
 # Checking characteristics of compilers and other programs
 # ===========================================================================
-AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,sdcc_cv_MM,
-echo "#include <stdio.h>" >_test_.c
-echo "" >>_test_.c
-$CPP -v -MM _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  sdcc_cv_MM="-MM"
+if test "$ac_cv_c_compiler_gnu" = "yes"; then
+  AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,sdcc_cv_MM,
+  echo "#include <stdio.h>" >_test_.c
+  echo "" >>_test_.c
+  $CPP -v -MM _test_.c 1>&5 2>&5
+  if test "$?" = "0"; then
+    sdcc_cv_MM="-MM"
+  else
+    sdcc_cv_MM="-M"
+  fi
+  rm -f _test_.*)
+  M_OR_MM=$sdcc_cv_MM
+
+  # This is the first time when CFLAGS are set/modified!!
+  bor_IS_VALID_OPTION(ggdb)
+  if test "$bor_cv_c_ggdb" = "yes"; then
+    CFLAGS="-ggdb ${CFLAGS}"
+  fi
+
+  bor_IS_VALID_OPTION(pipe)
+  if test "$bor_cv_c_pipe" = "yes"; then
+    CFLAGS="-pipe $CFLAGS"
+  fi
 else
-  sdcc_cv_MM="-M"
+  bor_IS_SUNPRO
+  if test "$bor_cv_c_compiler_sunpro" = "yes"; then
+    M_OR_MM="-xM1"
+  fi
 fi
-rm -f _test_.*)
-M_OR_MM=$sdcc_cv_MM
+
 AC_SUBST(M_OR_MM)
-
-# This is the first time when CFLAGS are set/modified!!
-adl_DD_COPT(CC, ggdb)
-if test "$sdcc_cv_CCggdb" = "yes"; then
-  CFLAGS="-ggdb ${CFLAGS}"
-fi
-
-adl_DD_COPT(CC, pipe)
-if test "$sdcc_cv_CCpipe" = "yes"; then
-  CFLAGS="-pipe $CFLAGS"
-fi
 
 
 # Checks for typedefs, structures, and compiler characteristics.
diff --git a/sim/ucsim/configure.in b/sim/ucsim/configure.in
--- a/sim/ucsim/configure.in
+++ b/sim/ucsim/configure.in
@@ -372,48 +372,39 @@ ucsim_ACCEPT_LENGTH_T
 # Macro definitions
 ###################
 
-# DD_COPT macro checks if the compiler specified as the 1st parameter
-# supports option specified as the 2nd parameter
-# For example: DD_COPT(CXX, fPIC)
+# Check whether the compiler for the current language is SunPRO.
 
-AC_DEFUN(DD_COPT, [
-AC_CACHE_CHECK(whether $$1 accepts -$2,ucsim_cv_$1$2,
-cat >_test_.c <<EOF
-int main(void) {return(0);}
-EOF
-$$1 -v -$2 -c _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  ucsim_cv_$1$2="yes"
-else
-  ucsim_cv_$1$2="no"
-fi
-rm -f _test_.* a.out)
+AC_DEFUN(bor_IS_SUNPRO,
+[AC_CACHE_CHECK([whether we are using the SunPRO _AC_LANG compiler],
+  [bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro],
+  [_AC_COMPILE_IFELSE([AC_LANG_PROGRAM([], [[#if !defined __SUNPRO_C && !defined __SUNPRO_CC
+       choke me
+#endif
+]])],
+    [bor_compiler_sunpro=yes],
+    [bor_compiler_sunpro=no])
+bor_cv_[]_AC_LANG_ABBREV[]_compiler_sunpro=$bor_compiler_sunpro
+])])
+
+# bor_IS_VALID_OPTION macro checks if the current compiler, selected by 
+# AC_LANG, supports option specified as the 1st parameter. The test fails if
+# the compiler returns an error or in case something is writeen to stderr.
+# For example: bor_VALID_OPT(fPIC)
+
+AC_DEFUN(bor_IS_VALID_OPTION,
+[ac_test_[]_AC_LANG_PREFIX[]FLAGS=${[]_AC_LANG_PREFIX[]FLAGS+set}
+bor_save_[]_AC_LANG_PREFIX[]FLAGS=$[]_AC_LANG_PREFIX[]FLAGS
+AC_CACHE_CHECK(whether $_AC_LANG_PREFIX accepts -$1, bor_cv_[]_AC_LANG_ABBREV[]_$1,
+  [bor_save_[]_AC_LANG_ABBREV[]_werror_flag=$ac_[]_AC_LANG_ABBREV[]_werror_flag
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=yes
+   
+   []_AC_LANG_PREFIX[]FLAGS="-$1"
+   AC_COMPILE_IFELSE([AC_LANG_PROGRAM()],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=yes],
+     [bor_cv_[]_AC_LANG_ABBREV[]_$1=no])
+   ac_[]_AC_LANG_ABBREV[]_werror_flag=$bor_save_[]_AC_LANG_ABBREV[]_werror_flag])
+   []_AC_LANG_PREFIX[]FLAGS=$bor_save_[]_AC_LANG_PREFIX[]FLAGS
 ])
-
-# DD_COPT_NO_IGNORE macro checks if the compiler specified as the
-# 1st parameter supports and doesn't ignore option specified as the
-# 2nd parameter
-# For example: DD_COPT_NO_IGNORE(CXX, fPIC)
-
-AC_DEFUN(DD_COPT_NO_IGNORE, [
-AC_CACHE_CHECK(whether $$1 accepts and doesn't ignore -$2,ucsim_cv_$1$2,
-cat >_test_.c <<EOF
-int main(void) {return(0);}
-EOF
-ucsim_cv_$1$2=$($$1 -v -$2 -c _test_.c 2>&1 1>&5)
-if test "$?" = "0"; then
-  expr "$ucsim_cv_$1$2" : '.*'-$2'.*ignored' 1>&5 2>&5
-  if test "$?" = "0"; then
-    ucsim_cv_$1$2="no"
-  else
-    ucsim_cv_$1$2="yes"
-  fi
-else
-  ucsim_cv_$1$2="no"
-fi
-rm -f _test_.* a.out)
-])
-
 
 # Checking characteristics of compilers and other programs
 # --------------------------------------------------------
@@ -501,55 +492,57 @@ esac
 
 SDCC_BUILD_BIGENDIAN
 
-AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,ucsim_cv_MM,
-echo "#include <stdio.h>" >_test_.c
-echo "" >>_test_.c
-$CXXCPP -v -MM _test_.c 1>&5 2>&5
-if test "$?" = "0"; then
-  ucsim_cv_MM="-MM"
-else
-  ucsim_cv_MM="-M"
-fi
-rm -f _test_.*)
-M_OR_MM=$ucsim_cv_MM
-AC_SUBST(M_OR_MM)
-
-# This is the first time when CFLAGS are set/modified!!
-
-DD_COPT(CXX, ggdb)
-DD_COPT(CXX, gstabs)
-if test "$ucsim_cv_CXXgstabs" = "yes"; then
-   gopt="-gstabs+ -g3"
-elif test "$ucsim_cv_CXXggdb" = "yes"; then
-     gopt="-ggdb -g3"
-else
-     gopt="-g"
-fi
-if test "$CXXFLAGS"x = x ;then
-        CXXFLAGS="$gopt"
-else
-        CXXFLAGS="$CXXFLAGS $gopt"
-fi
-
-DD_COPT(CXX, pipe)
-if test "$ucsim_cv_CXXpipe" = "yes"; then
-  CXXFLAGS="$CXXFLAGS -pipe"
-fi
-
 PICOPT=""
 SHAREDLIB="no"
-DD_COPT_NO_IGNORE(CXX, fPIC)
-if test "$ucsim_cv_CXXfPIC" = "yes"; then
-    PICOPT="-fPIC"
+
+if test "$ac_cv_cxx_compiler_gnu" = "yes"; then
+  AC_CACHE_CHECK(whether preprocessor accepts -MM or -M,ucsim_cv_MM,
+  echo "#include <stdio.h>" >_test_.c
+  echo "" >>_test_.c
+  $CXXCPP -v -MM _test_.c 1>&5 2>&5
+  if test "$?" = "0"; then
+    ucsim_cv_MM="-MM"
+  else
+    ucsim_cv_MM="-M"
+  fi
+  rm -f _test_.*)
+  M_OR_MM=$ucsim_cv_MM
+
+  # This is the first time when CFLAGS are set/modified!!
+
+  bor_IS_VALID_OPTION(ggdb)
+  bor_IS_VALID_OPTION(gstabs)
+  if test "$ucsim_cv_cxx_gstabs" = "yes"; then
+    gopt="-gstabs+ -g3"
+  elif test "$ucsim_cv_cxx_ggdb" = "yes"; then
+    gopt="-ggdb -g3"
+  else
+    gopt="-g"
+  fi
+  if test "$CXXFLAGS"x = x ;then
+    CXXFLAGS="$gopt"
+  else
+    CXXFLAGS="$CXXFLAGS $gopt"
+  fi
+
+  bor_IS_VALID_OPTION(pipe)
+  if test "$ucsim_cv_cxx_pipe" = "yes"; then
+    CXXFLAGS="$CXXFLAGS -pipe"
+  fi
 else
-    DD_COPT_NO_IGNORE(CXX, fpic)
-    if test "$ucsim_cv_CXXfpic" = "yes"; then
-        PICOPT="-fpic"
-    fi
+  bor_IS_SUNPRO
+  if test "$bor_cv_cxx_compiler_sunpro" = "yes"; then
+    M_OR_MM="-xM1"
+  fi
 fi
+
+# pic_flag is defined by AC_PROG_LIBTOOL
+PICOPT=$pic_flag
+
 if test "$PICOPT"x != "x"; then
     SHAREDLIB="yes"
 fi
+AC_SUBST(M_OR_MM)
 AC_SUBST(SHAREDLIB)
 AC_SUBST(PICOPT)
 
