* sim/ucsim/cmd.src/newcmdposix.cc, sim/ucsim/cmd.src/newcmdposixcl.h,   sim/ucsim/cmd.src/newcmdwin32.cc, sim/ucsim/cmd.src/newcmdwin32cl.h,   sim/ucsim/app.cc, sim/ucsim/appcl.h, sim/ucsim/configure,   sim/ucsim/configure.in, sim/ucsim/ddconfig_in.h, sim/ucsim/error.cc,   sim/ucsim/errorcl.h, sim/ucsim/option.cc, sim/ucsim/optioncl.h,   sim/ucsim/utils.cc, sim/ucsim/utils.h, sim/ucsim/cmd.src/Makefile.in,   sim/ucsim/avr.src/avr.cc, sim/ucsim/avr.src/avrcl.h,   sim/ucsim/cmd.src/bp.cc, sim/ucsim/cmd.src/bpcl.h,   sim/ucsim/cmd.src/cmdconf.cc, sim/ucsim/cmd.src/cmdgui.cc,   sim/ucsim/cmd.src/cmdmem.cc, sim/ucsim/cmd.src/cmdset.cc,   sim/ucsim/cmd.src/cmdsetcl.h, sim/ucsim/cmd.src/cmdstat.cc,   sim/ucsim/cmd.src/cmduc.cc, sim/ucsim/cmd.src/cmduccl.h,   sim/ucsim/cmd.src/cmdutil.cc, sim/ucsim/cmd.src/cmdutil.h,   sim/ucsim/cmd.src/command.cc, sim/ucsim/cmd.src/commandcl.h,   sim/ucsim/cmd.src/get.cc, sim/ucsim/cmd.src/getcl.h,   sim/ucsim/cmd.src/info.cc, sim/ucsim/cmd.src/newcmd.cc,   sim/ucsim/cmd.src/newcmdcl.h, sim/ucsim/cmd.src/set.cc,   sim/ucsim/cmd.src/show.cc, sim/ucsim/cmd.src/timer.cc,   sim/ucsim/hc08.src/hc08.cc, sim/ucsim/hc08.src/hc08cl.h,   sim/ucsim/s51.src/Makefile.in, sim/ucsim/s51.src/interrupt.cc,   sim/ucsim/s51.src/interruptcl.h, sim/ucsim/s51.src/pca.cc,   sim/ucsim/s51.src/pcacl.h, sim/ucsim/s51.src/port.cc,   sim/ucsim/s51.src/portcl.h, sim/ucsim/s51.src/serial.cc,   sim/ucsim/s51.src/serialcl.h, sim/ucsim/s51.src/timer0.cc,   sim/ucsim/s51.src/timer0cl.h, sim/ucsim/s51.src/timer1.cc,   sim/ucsim/s51.src/timer1cl.h, sim/ucsim/s51.src/timer2.cc,   sim/ucsim/s51.src/timer2cl.h, sim/ucsim/s51.src/uc390.cc,   sim/ucsim/s51.src/uc390cl.h, sim/ucsim/s51.src/uc390hw.cc,   sim/ucsim/s51.src/uc390hwcl.h, sim/ucsim/s51.src/uc51.cc,   sim/ucsim/s51.src/uc51cl.h, sim/ucsim/s51.src/wdt.cc,   sim/ucsim/s51.src/wdtcl.h, sim/ucsim/sim.src/hw.cc,   sim/ucsim/sim.src/hwcl.h, sim/ucsim/sim.src/mem.cc,   sim/ucsim/sim.src/memcl.h, sim/ucsim/sim.src/obsolete.cc,   sim/ucsim/sim.src/obsolete.h, sim/ucsim/sim.src/sim.cc,   sim/ucsim/sim.src/simcl.h, sim/ucsim/sim.src/stack.cc,   sim/ucsim/sim.src/stackcl.h, sim/ucsim/sim.src/test_mem_speed.cc,   sim/ucsim/sim.src/uc.cc, sim/ucsim/sim.src/uccl.h,   sim/ucsim/xa.src/xa.cc, sim/ucsim/xa.src/xacl.h,   sim/ucsim/z80.src/z80.cc, sim/ucsim/z80.src/z80cl.h:   ucsim WIN32 native port
git-svn-id: https://sdcc.svn.sourceforge.net/svnroot/sdcc/trunk/sdcc@4348 4a8a32a2-be11-0410-ad9d-d568d2c75423

diff --git a/sim/ucsim/configure b/sim/ucsim/configure
--- a/sim/ucsim/configure
+++ b/sim/ucsim/configure
@@ -468,7 +468,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK VERSION VERSIONHI VERSIONLO VERSIONP docdir enable_ucsim enable_dlso enable_51 enable_avr enable_z80 enable_hc08 enable_xa enable_serio CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CXXCPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB STRIP build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS ac_ct_CC LN_S ECHO ac_ct_STRIP CPP EGREP LIBTOOL LIBTOOL_DEPS LEX LEXLIB LEX_OUTPUT_ROOT YACC BISON_PLUS_PLUS SERIAL_AVAIL dl_ok DL panel_ok curses_ok CURSES_LIBS M_OR_MM SHAREDLIB PICOPT dlso_ok LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK VERSION VERSIONHI VERSIONLO VERSIONP docdir enable_ucsim enable_dlso enable_51 enable_avr enable_z80 enable_hc08 enable_xa enable_serio CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CXXCPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB STRIP build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS ac_ct_CC LN_S ECHO ac_ct_STRIP CPP EGREP LIBTOOL LIBTOOL_DEPS LEX LEXLIB LEX_OUTPUT_ROOT YACC BISON_PLUS_PLUS WINSOCK_AVAIL dl_ok DL panel_ok curses_ok CURSES_LIBS M_OR_MM SHAREDLIB PICOPT dlso_ok LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -8672,7 +8672,7 @@ fi
 
 fi
 if test ${LEX} = "flex"; then
-	cat >>confdefs.h <<\_ACEOF
+        cat >>confdefs.h <<\_ACEOF
 #define HAVE_FLEX 1
 _ACEOF
 
@@ -8939,7 +8939,9 @@ _ACEOF
 fi
 
 
-for ac_header in getopt.h
+
+
+for ac_header in getopt.h unistd.h termios.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -9087,307 +9089,6 @@ _ACEOF
 fi
 
 done
-
-
-for ac_header in unistd.h
-do
-as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking $ac_header usability" >&5
-echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <$ac_header>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_header_compiler=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
-
-# Is the header present?
-echo "$as_me:$LINENO: checking $ac_header presence" >&5
-echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <$ac_header>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_cxx_preproc_warn_flag
-    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
-echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
-    (
-      cat <<\_ASBOX
-## ------------------------------------------ ##
-## Report this to the AC_PACKAGE_NAME lists.  ##
-## ------------------------------------------ ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  eval "$as_ac_Header=\$ac_header_preproc"
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-
-fi
-if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
-_ACEOF
-
-fi
-
-done
-
-
-if test "${ac_cv_header_termios_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for termios.h" >&5
-echo $ECHO_N "checking for termios.h... $ECHO_C" >&6
-if test "${ac_cv_header_termios_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_termios_h" >&5
-echo "${ECHO_T}$ac_cv_header_termios_h" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking termios.h usability" >&5
-echo $ECHO_N "checking termios.h usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <termios.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_header_compiler=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
-
-# Is the header present?
-echo "$as_me:$LINENO: checking termios.h presence" >&5
-echo $ECHO_N "checking termios.h presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <termios.h>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_cxx_preproc_warn_flag
-    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: termios.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: termios.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: termios.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: termios.h: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: termios.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: termios.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: termios.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: termios.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: termios.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: termios.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: termios.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: termios.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: termios.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: termios.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: termios.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: termios.h: in the future, the compiler will take precedence" >&2;}
-    (
-      cat <<\_ASBOX
-## ------------------------------------------ ##
-## Report this to the AC_PACKAGE_NAME lists.  ##
-## ------------------------------------------ ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-echo "$as_me:$LINENO: checking for termios.h" >&5
-echo $ECHO_N "checking for termios.h... $ECHO_C" >&6
-if test "${ac_cv_header_termios_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_termios_h=$ac_header_preproc
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_termios_h" >&5
-echo "${ECHO_T}$ac_cv_header_termios_h" >&6
-
-fi
-if test $ac_cv_header_termios_h = yes; then
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_TERMIOS_H 1
-_ACEOF
-
-  SERIAL_AVAIL=1
-else
-  SERIAL_AVAIL=0
-
-fi
-
-
 
 
 if test "${ac_cv_header_curses_h+set}" = set; then
@@ -9697,6 +9398,7 @@ fi
 
 
 
+WINSOCK_AVAIL=0
 if test $ucsim_cv_socket = unknown; then
   if test "${ac_cv_header_winsock2_h+set}" = set; then
   echo "$as_me:$LINENO: checking for winsock2.h" >&5
@@ -9849,11 +9551,13 @@ _ACEOF
 _ACEOF
 
     ucsim_cv_socket="<winsock2.h>"
+    WINSOCK_AVAIL=1
 
 fi
 
 
 fi
+
 
 if test $ucsim_cv_socket != unknown; then
   cat >conftest.$ac_ext <<_ACEOF
@@ -10502,7 +10206,7 @@ _ACEOF
 # Checking for functions/libs
 # ===========================================================================
 if echo $ucsim_cv_socket|grep winsock2 >/dev/null 2>&1; then
-  LIBS="-lwsock32 $LIBS"
+  LIBS="-lws2_32 $LIBS"
 else
 
 echo "$as_me:$LINENO: checking for socket in -lsocket" >&5
@@ -11178,6 +10882,108 @@ done
 
 
 for ac_func in vsnprintf
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
+
+
+for ac_func in _vsnprintf
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -12250,9 +12056,9 @@ esac
 else
 #echo "CROSS ENDIAN"
     if $CXX -v 2>&1|grep "mingw" >/dev/null 2>&1; then
-	ac_cv_c_bigendian=no
+        ac_cv_c_bigendian=no
     else
-	: # FIXME
+        : # FIXME
     fi
 #echo "CROSS ENDIAN DONE"
 fi
@@ -12329,9 +12135,9 @@ else
      gopt="-g"
 fi
 if test "$CXXFLAGS"x = x ;then
-	CXXFLAGS="$gopt"
+        CXXFLAGS="$gopt"
 else
-	CXXFLAGS="$CXXFLAGS $gopt"
+        CXXFLAGS="$CXXFLAGS $gopt"
 fi
 
 
@@ -12407,7 +12213,7 @@ echo "$as_me:$LINENO: result: $ucsim_cv_CXXfpic" >&5
 echo "${ECHO_T}$ucsim_cv_CXXfpic" >&6
 
     if test "$ucsim_cv_CXXfpic" = "yes"; then
-	PICOPT="-fpic"
+        PICOPT="-fpic"
     fi
 fi
 if test "$PICOPT"x != "x"; then
@@ -14575,13 +14381,13 @@ _ACEOF
 
 else
     if $CXX -v 2>&1|grep "mingw" >/dev/null 2>&1; then
-	ac_cv_sizeof_char=1
-	ac_cv_sizeof_short=2
-	ac_cv_sizeof_int=4
-	ac_cv_sizeof_long=4
-	ac_cv_sizeof_long_long=4
+        ac_cv_sizeof_char=1
+        ac_cv_sizeof_short=2
+        ac_cv_sizeof_int=4
+        ac_cv_sizeof_long=4
+        ac_cv_sizeof_long_long=4
     else
-	: # FIXME
+        : # FIXME
     fi
 #echo
 fi
@@ -14589,24 +14395,24 @@ fi
 type_name()
 {
     if expr "$ac_cv_sizeof_char" '>=' "$1" >/dev/null; then
-	echo "char"
-	exit
+        echo "char"
+        exit
     fi
     if expr "$ac_cv_sizeof_short" '>=' "$1" >/dev/null; then
-	echo "short"
-	exit
+        echo "short"
+        exit
     fi
     if expr "$ac_cv_sizeof_int" '>=' "$1" >/dev/null; then
-	echo "int"
-	exit
+        echo "int"
+        exit
     fi
     if expr "$ac_cv_sizeof_long" '>=' "$1" >/dev/null; then
-	echo "long"
-	exit
+        echo "long"
+        exit
     fi
     if expr "$ac_cv_sizeof_long_long" '>=' "$1" >/dev/null; then
-	echo "long long"
-	exit
+        echo "long long"
+        exit
     fi
     echo "long long"
 }
@@ -15340,7 +15146,7 @@ s,@LEXLIB@,$LEXLIB,;t t
 s,@LEX_OUTPUT_ROOT@,$LEX_OUTPUT_ROOT,;t t
 s,@YACC@,$YACC,;t t
 s,@BISON_PLUS_PLUS@,$BISON_PLUS_PLUS,;t t
-s,@SERIAL_AVAIL@,$SERIAL_AVAIL,;t t
+s,@WINSOCK_AVAIL@,$WINSOCK_AVAIL,;t t
 s,@dl_ok@,$dl_ok,;t t
 s,@DL@,$DL,;t t
 s,@panel_ok@,$panel_ok,;t t
